// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwR3PoZr1vXw7O7rMDVXKCsjKo3X3UH7E',
    appId: '1:585279219951:web:3dcf43ad93503a9ef3931a',
    messagingSenderId: '585279219951',
    projectId: 'appointment-booking-app-b138c',
    authDomain: 'appointment-booking-app-b138c.firebaseapp.com',
    storageBucket: 'appointment-booking-app-b138c.appspot.com',
    measurementId: 'G-YGG703VYGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTjLuPehJhTz8XGJXD8xsQSRJ1Ln4Eyao',
    appId: '1:585279219951:android:17bc5f2e27b53a5bf3931a',
    messagingSenderId: '585279219951',
    projectId: 'appointment-booking-app-b138c',
    storageBucket: 'appointment-booking-app-b138c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3bC-xMxaP1k0Q_dnMfYwavQpAq4cLRLU',
    appId: '1:585279219951:ios:8b6759df46ccfb42f3931a',
    messagingSenderId: '585279219951',
    projectId: 'appointment-booking-app-b138c',
    storageBucket: 'appointment-booking-app-b138c.appspot.com',
    iosBundleId: 'com.example.appointmentBookingApp',
  );
}
